### ISSUE TITLE
Issue regards of corsair Ram?

### ISSUE THREAD

**Issue by UsmanQA** [ChromaControl/ChromaControl#16]
I notice from time to time that ram (corsair vengeance RGB pro) I currently have seems to be always stuck on fixed colour (usually orange). As well the logo on my motherboard (B450-F) doesn't seem to light up at all. I just generally want to see if anything I can do to help to improve this software since its amazing indeed! 

Yesterday, it would work perfectly and sync everything in terms of my RGB products, it just now I have these two issues mentioned above. This is my first time submitting an issue on GitHub but if you need any information or logs to diagnose this, do let me know.

I attached images of what it currently looks like and as well red triangle on that appears on my ram (iCue)

![WhatsApp Image 2021-01-28 at 20 44 03](https://user-images.githubusercontent.com/43070603/106196645-97423d00-61a9-11eb-9585-719cb7e21322.jpeg)

![image](https://user-images.githubusercontent.com/43070603/106196526-6eba4300-61a9-11eb-8612-c3c91c8b0d04.png)

**Comment by zbzbzbzb** [comment]
The same thing happens to my RAM from time to time, I dont think its an issue with this software but rather ICue. If it happens go into task manager and filter for most cpu intensive processes, there will be one that says ICUE service for {something} thats taking about 10% CPU usage. right click on it and press end task, then kill the normal ICUE process and then restart ICUE that should bring your RGB back

**Comment by UsmanQA** [comment]
> The same thing happens to my RAM from time to time, I dont think its an issue with this software but rather ICue. If it happens go into task manager and filter for most cpu intensive processes, there will be one that says ICUE service for {something} thats taking about 10% CPU usage. right click on it and press end task, then kill the normal ICUE process and then restart ICUE that should bring your RGB back

I tried that and unfortunately, that doesn't seem to work regards of my ram issue (red triangle is still there on my ram) however my motherboard logo has come up, so thanks for that!

**Comment by AndrewBabbitt97** [comment]
The red triangle in iCUE is concerning as that's telling me the issue lies in iCUE no?

As for ASUS devices, I do have concerns around using the AURA module with the Corsair module as Corsair added ASUS device support. Haven't found a way to disable ASUS device support in iCUE. I can see conflicts happening there.

**Comment by UsmanQA** [comment]
> The red triangle in iCUE is concerning as that's telling me the issue lies in iCUE no?
> 
> As for ASUS devices, I do have concerns around using the AURA module with the Corsair module as Corsair added ASUS device support. Haven't found a way to disable ASUS device support in iCUE. I can see conflicts happening there.

So currently the motherboard's logo now seems to work. I think possibly on lines like you said regards of Asus's aura support within iCue that might cause conflicts, but for me it works. 

But has been consistent is that ram RGB doesn't seem to work well at all. If I remove software, the ram's RGB works well..soon as install you're software. It doesn't play nice.

I have feeling it's more to do with iCue having issue. I can try reinstalling iCue right now get back to you to see if that work?





M

**Comment by UsmanQA** [comment]
Quick update, did full clean, reinstall of iCue and now red triangle is gone and ram of RGB works..for now. I want to see if this last tomorrow. If it does, I will close issue and there. Problem solved hopefully!

**Comment by UsmanQA** [comment]
New update (sorry for delay) unfortunately the problem has just returned... (red triangle on Corsair ram)

**Comment by AndrewBabbitt97** [comment]
Very odd. I believe there's a way for Aura to control Corsair RGB ram as well, so I'd make sure none of that's enabled. 

Beyond that, the triangle on iCUE definitely says that there's something wrong on iCUE with it. Is there any additional info when you hover your mouse cursor over the triangle?

I just don't have enough context as to why iCUE is having issues.

**Comment by UsmanQA** [comment]
It is extremely weird. I also did reinstall of Razer and as well chroma control. Nothing. I wish I can give more context but I can't seem to get any information about red triangle. 

Is there any logs I can check or some way to help? I know that if I remove chroma control. The red triangle disappears..

**Comment by AndrewBabbitt97** [comment]
@UsmanQA 

If you could get me logs from %localappdata%\Packages\ChromaControl.Corsair_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs that would be useful.

If the logs show ChromaControl starting and loading devices the issue lies somewhere in iCUE and theres not really anything I can do.

You have also updated the firmware on all of the ram sticks correct?

**Comment by UsmanQA** [comment]
@AndrewBabbitt97 

Of course, here is the log (seems fine to me?):
[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/5900787/Corsair.log)

I also provide Asus log (in case?):
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/5900807/ASUS.log)

That's honestly understandable. I still don't understand as to why iCue having an issue with only the ram.

The firmware on all of the ram sticks is up to date. I did try to use force update function but it still doesn't work.
![image](https://user-images.githubusercontent.com/43070603/106399803-ceffed80-6412-11eb-8f87-384b3b56138f.png)

**Comment by AndrewBabbitt97** [comment]
I havent personally seen any issues with this, but could you also go close iCUE and delete the ASUS folder from C:\Program Files (x86)\Corsair\CORSAIR iCUE Software\plugins or just move it out of there for the time being.

Is your lighting node core working fine with Chroma Control?

**Comment by UsmanQA** [comment]
> I havent personally seen any issues with this, but could you also go close iCUE and delete the ASUS folder from C:\Program Files (x86)\Corsair\CORSAIR iCUE Software\plugins or just move it out of there for the time being.
> 
> Is your lighting node core working fine with Chroma Control?

Sure! I honestly don't mind trying anything at this point. I move it for now.

Lighting node core works perfectly fine, as you can see my three fans on previous images being in sync perfectly. Hence the reason why I am really confused about it...

**Comment by UsmanQA** [comment]
@AndrewBabbitt97 

So I did what you asked and well. it syncs! no red triangle on the ram?

![image](https://user-images.githubusercontent.com/43070603/106400123-9234f600-6414-11eb-86fd-00ad7ddd8e36.png)

**Comment by AndrewBabbitt97** [comment]
Okay cool! So please monitor this over like the next week after restarts and stuff and let me know if it's still working after. Just want to make sure it continues to work.

If this ends up being the actual fix, I'll get it documented for install when I do the stable release sometime in the next two weeks.

**Comment by UsmanQA** [comment]
Honestly, I will do so! For now, it seems to work as you can see. I try to keep an eye on when it doesn't seem to work. But thanks for your help.

**Comment by heavyoak** [comment]
hey @op thats a corsair issue, fixed by restarting icue.

**Comment by UsmanQA** [comment]
@AndrewBabbitt97 new update and it seems the issue has come back again. I notice ever since we did the fix. Sometimes the ram will be sync with rest of RGB and then sometimes it wouldn't be (just like right know as we speak).

Asus folder hasn't reappeared in iCue folder.

**Comment by AndrewBabbitt97** [comment]
Did the triangle show up in iCUE again?

**Comment by UsmanQA** [comment]
> Did the triangle show up in iCUE again?

I just checked and I should have mentioned that. Yeah, the red triangle still appears on iCue with the ram.

**Comment by AndrewBabbitt97** [comment]
Given the fact that the lighting node core works fine but not the ram, this issue is something happening in iCUE. Due to this, there's nothing on my end that I can do. This would have to be resolved with the iCUE developers at Corsair. I just use iCUE as an interface to interact with their devices. 😔

**Comment by UsmanQA** [comment]
> Given the fact that the lighting node core works fine but not the ram, this issue is something happening in iCUE. Due to this, there's nothing on my end that I can do. This would have to be resolved with the iCUE developers at Corsair. I just use iCUE as an interface to interact with their devices. 😔

I completely understand so don't worry about it! I wish I can do something about this but oh well.

I was going to ask and that is, do you have corsair RAM (VENGEANCE RGB PRO) on your computer and if so. I assume it works perfectly?

**Comment by AndrewBabbitt97** [comment]
No, I use Trident Z RGB and control it through AURA.

I may have some corsair ram laying around somewhere, I'll have to hunt it down though.

**Comment by AndrewBabbitt97** [comment]
Issue is more than likely Corsair SDK related. The more people that use the corsair side the more I realize how buggy their SDK is. This is all unfortunately out of my control.
