### ISSUE TITLE
Chroma Control Asus Unreachable 

### ISSUE THREAD

**Issue by tannerveyron** [ChromaControl/ChromaControl#65]
I never had a problem with either the Aura Connect or the new Chroma Control. I recently updated everything in the armoury create and now I am not able to use Chroma Control in razer synapse. I have done a fresh install on the armory create, razer synapse, and chroma control, nothing has solved it. IDK if the update patched chroma control or if somehow I reinstalled it wrong

Amazing Software! Keep up the great work!

![aura](https://user-images.githubusercontent.com/55293726/113079495-27e5cb00-91a3-11eb-95b9-264a95e86867.PNG)
![aura2](https://user-images.githubusercontent.com/55293726/113080479-fe2da380-91a4-11eb-9419-01d058471dfb.PNG)
![aura3](https://user-images.githubusercontent.com/55293726/113080608-29b08e00-91a5-11eb-9f7a-ca3a93d59faa.PNG)

**Comment by Zifuta** [comment]
I have the same problem, Chroma control - Asus unreachable

**Comment by AndrewBabbitt97** [comment]
Need logs %localappdata%\Local\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by I2obiN** [comment]
Same issue, unreachable in chroma control
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6327671/ASUS.log)

**Comment by guaycuru** [comment]
Same issue, the log doesn't seem to indicate any issues.
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6377233/ASUS.log)

**Comment by I2obiN** [comment]
Resolved this, required armoury crate to update all devices. Might be worth sticking something in the log to say "check Armoury Crate or ASUS software is updated". As a troubleshooting step.

**Comment by I2obiN** [comment]
Unreachable again, this time everything is updated

**Comment by I2obiN** [comment]
If I disable the device in synapse then restart it just disappears completely. Even if i click this nothing happens,
![image](https://user-images.githubusercontent.com/7683830/116630264-e5064700-a94a-11eb-81c9-13bd06a5aec3.png)

**Comment by I2obiN** [comment]
After reinstall i am seeing this in log now

![image](https://user-images.githubusercontent.com/7683830/116630681-93aa8780-a94b-11eb-953f-e457664bc671.png)

**Comment by AndrewBabbitt97** [comment]
That log item indicates a Synapse issue. Everything on the Chroma Control side is working. There were a lot of Synapse issues around the time this was opened. Please verify that issue is still a problem and can look into it more.

**Comment by AndrewBabbitt97** [comment]
Closing due to inactivity.

**Comment by leifdotwav** [comment]
re-opening issue. this exact problem started for me, and i'm unable to view any sort of logs for the app from the path that was provided. syncing stopped working for me, then i updated synapse, and it still wouldn't work. i tried fiddling around with AURA settings, and restarting all the requisite apps, but nothing seemed to happen. if you could look into this, that'd be amazing.
